name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Unit tests
        run: bash ./gradlew test --stacktrace
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build pluginbasicutils
      run: bash ./gradlew assemble --stacktrace
    - name: Upload debug pluginbasicutils
      uses: actions/upload-artifact@v1
      with:
        name: pluginbasicutils-debug
        path: pluginbasicutils/build/outputs/aar/pluginbasicutils-debug.aar
    - name: Upload release pluginbasicutils
      uses: actions/upload-artifact@v1
      with:
        name: pluginbasicutils-release
        path: pluginbasicutils/build/outputs/aar/pluginbasicutils-release.aar        
