name: Android CI

on:
  push:
    branches: [ main ]

jobs:

  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Unit tests
        run: bash ./gradlew test --stacktrace
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build pluginbasicutils
      run: bash ./gradlew assemble --stacktrace
    - name: Upload debug pluginbasicutils
      uses: actions/upload-artifact@v1
      with:
        name: pluginbasicutils-debug
        path: pluginbasicutils/build/outputs/aar/pluginbasicutils-debug.aar
    - name: Upload release pluginbasicutils
      uses: actions/upload-artifact@v1
      with:
        name: pluginbasicutils-release
        path: pluginbasicutils/build/outputs/aar/pluginbasicutils-release.aar
    - name: Set release name
      run: echo ::set-env name=RELEASE_NAME::$(echo ${GITHUB_REF:11})
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ env.RELEASE_NAME }}
        body: |
          What is new :
            - First Release
          draft: false
          prerelease: false
