name: Android CI

on:
  push:
    tags:
      - 'v*'

jobs:

  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Unit tests
        run: bash ./gradlew test --stacktrace



  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build pluginbasicutils
        run: bash ./gradlew assemble --stacktrace

      - name: Upload debug pluginbasicutils
        uses: actions/upload-artifact@v1
        with:
          name: pluginbasicutils-debug
          path: pluginbasicutils/build/outputs/aar/pluginbasicutils-debug.aar

      - name: Upload release pluginbasicutils
        uses: actions/upload-artifact@v1
        with:
          name: pluginbasicutils-release
          path: pluginbasicutils/build/outputs/aar/pluginbasicutils-release.aar

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true
          prerelease: false
          body: |
            What is new :
              - First Release

      - name: Release Upload pluginbasicutils-debug
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: pluginbasicutils/build/outputs/aar/pluginbasicutils-debug.aar
          asset_name: pluginbasicutils-debug.aar
          asset_content_type: application/aar

      - name: Release Upload pluginbasicutils-release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: pluginbasicutils/build/outputs/aar/pluginbasicutils-release.aar
          asset_name: pluginbasicutils-release.aar
          asset_content_type: application/aar
